In [4]:
import pandas as pd
import glob


csv_files = glob.glob("WorldCup_Stats/*.csv") 
dataframes = [pd.read_csv(file) for file in csv_files]


crick_df = pd.concat(dataframes, ignore_index=True)


crick_df.head()

,Unnamed: 0.1,Unnamed: 0,date,venue,match_category,team_1,team_2,team_1_runs,team_1_wickets,team_2_runs,team_2_wickets,result,pom,best_batters,best_bowlers,commentary_line,world_cup_year,host_country
0,0,11,NaN,Nottingham,League-Match,PAK,SL,330.0,6.0,138.0,0.0,Pakistan won by 192 runs,Zaheer Abbas,NaN,NaN,NaN,1975,England
1,1,5,NaN,Leeds,League-Match,EAf,IND,120.0,0.0,123.0,0.0,India won by 10 wickets (with 181 balls remain...,Farokh Engineer,NaN,NaN,NaN,1975,England
2,2,12,1975-06-18,Leeds,Semi-Final,ENG,AUS,93.0,0.0,94.0,6.0,Australia won by 4 wickets (with 188 balls rem...,Gary Gilmour,NaN,NaN,NaN,1975,England
3,3,8,1975-06-14,Birmingham,League-Match,ENG,EAf,290.0,5.0,94.0,0.0,England won by 196 runs,John Snow,NaN,NaN,NaN,1975,England
4,4,13,NaN,The Oval,Semi-Final,NZ,WI,158.0,0.0,159.0,5.0,West Indies won by 5 wickets (with 119 balls r...,Alvin Kallicharran,NaN,NaN,NaN,1975,England

Assume null recodes as which contains all columns are null

In [5]:
#Data exploration
print(crick_df.info())
print(crick_df.describe())

# Remove duplicate records & Remove rows with null values
crick_df.drop_duplicates(inplace=True)
crick_df.dropna(how='all' ,inplace=True)

crick_df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0.1     528 non-null    int64
 1   Unnamed: 0       528 non-null    int64
 2   date             364 non-null    object
 3   venue            528 non-null    object
 4   match_category   528 non-null    object
 5   team_1           528 non-null    object
 6   team_2           528 non-null    object
 7   team_1_runs      518 non-null    float64
 8   team_1_wickets   518 non-null    float64
 9   team_2_runs      513 non-null    float64
 10  team_2_wickets   513 non-null    float64
 11  result           528 non-null    object
 12  pom              510 non-null    object
 13  best_batters     250 non-null    object
 14  best_bowlers     250 non-null    object
 15  commentary_line  83 non-null     object
 16  world_cup_year   528 non-null    int64
 17  host_country     528 non-null    object
dtypes: float64(4), int64(3), object(11)
memory usage: 74.4+ KB
None
       Unnamed: 0.1  Unnamed: 0  team_1_runs  team_1_wickets  team_2_runs  \
count    528.000000  528.000000   518.000000      518.000000   513.000000
mean      21.871212   21.034091   243.239382        4.590734   198.643275
std       14.307231   13.915398    75.108565        3.465005    59.732864
min        0.000000    0.000000     1.000000        0.000000    24.000000
25%       10.000000    9.000000   197.000000        0.000000   158.000000
50%       20.000000   20.000000   244.000000        6.000000   204.000000
75%       33.000000   32.000000   292.000000        8.000000   235.000000
max       55.000000   53.000000   428.000000        9.000000   383.000000

       team_2_wickets  world_cup_year
count      513.000000      528.000000
mean         2.777778     2003.373106
std          3.044163       13.352007
min          0.000000     1975.000000
25%          0.000000     1992.000000
50%          2.000000     2003.000000
75%          5.000000     2015.000000
max          9.000000     2023.000000

,Unnamed: 0.1,Unnamed: 0,date,venue,match_category,team_1,team_2,team_1_runs,team_1_wickets,team_2_runs,team_2_wickets,result,pom,best_batters,best_bowlers,commentary_line,world_cup_year,host_country
0,0,11,NaN,Nottingham,League-Match,PAK,SL,330.0,6.0,138.0,0.0,Pakistan won by 192 runs,Zaheer Abbas,NaN,NaN,NaN,1975,England
1,1,5,NaN,Leeds,League-Match,EAf,IND,120.0,0.0,123.0,0.0,India won by 10 wickets (with 181 balls remain...,Farokh Engineer,NaN,NaN,NaN,1975,England
2,2,12,1975-06-18,Leeds,Semi-Final,ENG,AUS,93.0,0.0,94.0,6.0,Australia won by 4 wickets (with 188 balls rem...,Gary Gilmour,NaN,NaN,NaN,1975,England
3,3,8,1975-06-14,Birmingham,League-Match,ENG,EAf,290.0,5.0,94.0,0.0,England won by 196 runs,John Snow,NaN,NaN,NaN,1975,England
4,4,13,NaN,The Oval,Semi-Final,NZ,WI,158.0,0.0,159.0,5.0,West Indies won by 5 wickets (with 119 balls r...,Alvin Kallicharran,NaN,NaN,NaN,1975,England
5,5,1,NaN,Birmingham,League-Match,NZ,EAf,309.0,5.0,128.0,8.0,New Zealand won by 181 runs,Glenn Turner,NaN,NaN,NaN,1975,England
6,6,7,NaN,Birmingham,League-Match,PAK,WI,266.0,7.0,267.0,9.0,West Indies won by 1 wicket (with 2 balls rema...,Sarfraz Nawaz,NaN,NaN,NaN,1975,England
7,7,2,NaN,Leeds,League-Match,AUS,PAK,278.0,7.0,205.0,0.0,Australia won by 73 runs,Dennis Lillee,NaN,NaN,NaN,1975,England
8,8,11,NaN,Nottingham,League-Match,PAK,SL,330.0,6.0,138.0,0.0,Pakistan won by 192 runs,Zaheer Abbas,NaN,NaN,NaN,1975,England
9,9,4,1975-06-11,Nottingham,League-Match,ENG,NZ,266.0,6.0,186.0,0.0,England won by 80 runs,Keith Fletcher,NaN,NaN,NaN,1975,England

Since earlier assumption there are some null values in runs columns. Hence, it is unable to remove outlies.

In [6]:
#Adding new columns to the DataFrame: match_status 
crick_df['match_status'] = crick_df['result'].apply(
    lambda x: 'abandoned' if 'abandoned' in x.lower() else 'played'
)

crick_df.head(10)

,Unnamed: 0.1,Unnamed: 0,date,venue,match_category,team_1,team_2,team_1_runs,team_1_wickets,team_2_runs,team_2_wickets,result,pom,best_batters,best_bowlers,commentary_line,world_cup_year,host_country,match_status
0,0,11,NaN,Nottingham,League-Match,PAK,SL,330.0,6.0,138.0,0.0,Pakistan won by 192 runs,Zaheer Abbas,NaN,NaN,NaN,1975,England,played
1,1,5,NaN,Leeds,League-Match,EAf,IND,120.0,0.0,123.0,0.0,India won by 10 wickets (with 181 balls remain...,Farokh Engineer,NaN,NaN,NaN,1975,England,played
2,2,12,1975-06-18,Leeds,Semi-Final,ENG,AUS,93.0,0.0,94.0,6.0,Australia won by 4 wickets (with 188 balls rem...,Gary Gilmour,NaN,NaN,NaN,1975,England,played
3,3,8,1975-06-14,Birmingham,League-Match,ENG,EAf,290.0,5.0,94.0,0.0,England won by 196 runs,John Snow,NaN,NaN,NaN,1975,England,played
4,4,13,NaN,The Oval,Semi-Final,NZ,WI,158.0,0.0,159.0,5.0,West Indies won by 5 wickets (with 119 balls r...,Alvin Kallicharran,NaN,NaN,NaN,1975,England,played
5,5,1,NaN,Birmingham,League-Match,NZ,EAf,309.0,5.0,128.0,8.0,New Zealand won by 181 runs,Glenn Turner,NaN,NaN,NaN,1975,England,played
6,6,7,NaN,Birmingham,League-Match,PAK,WI,266.0,7.0,267.0,9.0,West Indies won by 1 wicket (with 2 balls rema...,Sarfraz Nawaz,NaN,NaN,NaN,1975,England,played
7,7,2,NaN,Leeds,League-Match,AUS,PAK,278.0,7.0,205.0,0.0,Australia won by 73 runs,Dennis Lillee,NaN,NaN,NaN,1975,England,played
8,8,11,NaN,Nottingham,League-Match,PAK,SL,330.0,6.0,138.0,0.0,Pakistan won by 192 runs,Zaheer Abbas,NaN,NaN,NaN,1975,England,played
9,9,4,1975-06-11,Nottingham,League-Match,ENG,NZ,266.0,6.0,186.0,0.0,England won by 80 runs,Keith Fletcher,NaN,NaN,NaN,1975,England,played